export const ADD_WIDGET_SET_NAME = 'ADD_WIDGET_SET_NAME';
export const ADD_WIDGET = 'ADD_WIDGET';
export const SETTINGS_SET_NAME = 'SETTINGS_SET_NAME';
export const SETTINGS_SET_COUNT = 'SETTINGS_SET_COUNT';
export const SETTINGS_SET_COLOR = 'SETTINGS_SET_COLOR';
